In [ ]:
import numpy as np

In [ ]:
altezza = [1.73, 1.68, 1.71, 1.89, 1.70]
peso = [65.4, 59.2, 63.6, 88.4, 68.7]

In [ ]:
np_altezza = np.array(altezza)
np_peso = np.array(peso)

In [ ]:
type(np_altezza)

numpy.ndarray

In [ ]:
bmi = np_peso / (np_altezza ** 2)
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 23.7716263 ])

In [ ]:
test = np.array([1.0, "is", True])

In [ ]:
test

array(['1.0', 'is', 'True'], dtype='<U32')

In [ ]:
bmi >= 21.5

array([ True, False,  True,  True,  True])

In [ ]:
bmi[ bmi >= 21.5 ]

array([21.85171573, 21.75028214, 24.7473475 , 23.7716263 ])

In [ ]:
my_random_variable = np.random.normal(loc=20, scale=2, size=20000)

In [ ]:
len(my_random_variable)

20000

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/iris.txt')

In [ ]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [ ]:
df.shape

(150, 5)

In [ ]:
df.dtypes

Sepal.Length    float64
Sepal.Width     float64
Petal.Length    float64
Petal.Width     float64
Species          object
dtype: object

In [ ]:
df.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [ ]:
df.sort_values('Sepal.Length', ascending=False)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

In [ ]:
# df.sort_values(['Sepal.Length', 'Sepal.Width'])
df.sort_values(by=['Sepal.Length', 'Sepal.Width'], ascending=[True, False])

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [ ]:
df['Sepal.Length'] > 4.7

0       True
1       True
2      False
3      False
4       True
       ...  
145     True
146     True
147     True
148     True
149     True
Name: Sepal.Length, Length: 150, dtype: bool

## Part 3
13 de Junho de 2023